### ISSUE TITLE
Spurious variable shadowing warning

### ISSUE THREAD

**Issue by Fyren** [alliedmodders/sourcepawn#135]
Commit bb83d1b290fc83c54b94911929581970079a8234 seems to sometimes cause the compiler to incorrectly warn that a variable is being shadowed.  Here's a test case:

```
stock unused() {
    buffer
}

public void main() {
    char buffer[2];
    buffer[0] = 2;
}
```
Compiling this results in `warning 219: local variable "buffer" shadows a variable at a preceding level`.  Prior to this commit, no warning is emitted.
The unused stock appears to have to have an error of some kind involving an identifier with the code later using the same identifier.  For example, `stock unused() { char buffer[2]; foo }` does not cause the warning to be emitted.

**Comment by peace-maker** [comment]
Here's another test case that this commit triggered new errors with.

```sourcepawn
stock int unused()
{
	Test test = view_as<Test>(1);
	if (style == Test_B)
		return 1;
	return 0;
}

enum Test:
{
	Test_A,
	Test_B
}; // error 021: symbol already defined: "Test_B"

public void OnPluginStart()
{
	Test test = view_as<Test>(1);
	PrintToServer("%d", test);
}
```

**Comment by peace-maker** [comment]
It's because of this change here https://github.com/alliedmodders/sourcepawn/commit/bb83d1b290fc83c54b94911929581970079a8234#diff-6e6ab2dad1a895a7203f2d543f9459a1L2484

Previously it always errored, because procedual calls were force-disabled. I don't really understand the new logic, but I'd think we'd just want to return error() in that else branch and remove all the symbol lookup? @dvander

**Comment by peace-maker** [comment]
Summing up the IRC discussion few weeks ago:

Before #123 `sc_allowproccall` was always forced to `false` in SourcePawn, because procedual function calls without parenthesis were disabled. That caused the compiler to always return the `error(17,st)` and never run the other logic after it. (https://github.com/alliedmodders/sourcepawn/commit/bb83d1b290fc83c54b94911929581970079a8234#diff-6e6ab2dad1a895a7203f2d543f9459a1L2485)

My suggestion about always returning `error` again in the previous comment was effecively undoing #123 - with the exception that the compiler now printed `compiler bug: calling stock \"%s\" that has no generated code` when using stocks as callbacks instead of calling random memory.
On the other hand the change fixed this issue with identifiers being "defined" in unused functions.

**Comment by Fyren** [comment]
The test case in the original comment now compiles without warning, probably due to the changes in #371.  The test case in the first reply still errors.

**Comment by dvander** [comment]
Nice, guess we can close it now.
