### ISSUE TITLE
Can't get Angles with GetClientEyeAngles in enum struct.

### ISSUE THREAD

**Issue by Bara** [alliedmodders/sourcepawn#301]
Here's the test case with compile error and outputs for the working methods:
https://pastebin.com/aXh5Nsiu

**Comment by jason-e** [comment]
Chiming in to say: this issue also happens with old-style enum structs as well, it is not unique to the new syntax. Would be great to have it fixed.

**Comment by dvander** [comment]
Thanks for the report. This should indeed be fixed, but it will be difficult (unless I can find a surgical hack). The root of the issue is that the compiler does not really have types internally, and the only way it can represent an array type is through the same data structure that represents variables.

This obviously poses a problem for multi-dimensional arrays, since you need a separate type to represent inner dimensions. The compiler works around this by creating a hidden variable for each extra dimension. For example, "int x[MAXPLAYERS][3]" will actually have two definitions of "x", one for the outer dimension, and a hidden one for the inner.

How does this relate to enum structs? Well, enum structs don't allow multi-dimensional arrays, so the compiler doesn't bother creating symbols for embedded arrays. Instead it uses some really awful hacks to pretend there's a symbol there, just long enough to do some immediate type checking. Then it's gone, and the expression devolves to an anonymous array which does not have size information.

By the time the compiler is checking your function call, the size information is long gone.

I can think of two fixes for this. The difficult fix is also the proper one: remove the ugly hack, and create hidden symbols for array types within enum structs. The hack is ancient, I would only feel comfortable removing it for modern enum structs. The quicker solution would be to propagate the size through the `value` mechanism in the expression parser, so the argument checker can read it. But that is an extra smearing of hacks on a towering layer cake of hacks, and I'm hoping not to do that.
