### ISSUE TITLE
spcomp exit code 3221225477 - no eval on "else if {"

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#321]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/alliedmodders/sourcemod/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.

# Environment
  * Operating System version:  Win 10
  * Game/AppID (with version if applicable): NA
  * Current SourceMod version: 1.10
  * Current SourceMod snapshot: 6380
  * Current Metamod: Source snapshot: NA
  - [X] I have updated SourceMod to the [latest version](https://www.sourcemod.net/downloads.php) and it still happens.
  - [ ] I have updated SourceMod to the [latest snapshot](https://www.sourcemod.net/downloads.php?branch=dev) and it still happens.
  - [NA] I have updated SourceMM to the [latest snapshot](https://sourcemm.net/downloads.php?branch=dev) and it still happens.

# Description
spcomp exit code 3221225477 with no warning for missing parenthesis of `else if {`

# Problematic Code (or Steps to Reproduce)
  ```
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

ConVar g_cvarTest;

public void OnPluginStart() {
	HookEvent("item_pickup",  event_ItemPickup, EventHookMode_Pre);
}

public Action event_ItemPickup(Event event, const char[] name, bool dontBroadcast) {
	if (g_cvarTest == null) {
		return Plugin_Handled;
	}
	else if {
		int client = GetClientOfUserId(event.GetInt("userid"));
		if (client <= 0) {
			return Plugin_Handled;
		}
	}
 
	return Plugin_Continue;
}
  ```

**Comment by Fyren** [comment]
The problem in the original code posted is in parsing constructs with a required test, which means things like while loops as Headline said.  Simply doing `if { int x = 1; }` will hit the same assert as the original report.  WIthout the assignment, it might take some other path that results in an expected error, though.

As far as I can tell, this problem was incidentally fixed with https://github.com/alliedmodders/sourcepawn/commit/00dc17148b85bf7e045e6fe15035a6644d4c9d6e.  Testing against master (or the version of SP pinned by SM 1.10) results in the expected error, `error 001: expected token: "(", but found "{`.
