### ISSUE TITLE
Segfault with invalid methodmap declaration

### ISSUE THREAD

**Issue by Sikarii** [alliedmodders/sourcepawn#333]
Following code seems to segfault both the 1.9 and 1.10(?) compilers:

### Test case
```
methodmap break TestingA < StringMap
{
    public TestingA()
    {
        return view_as<TestingA>(new StringMap());
    }

    public void Test()
    {
        this.SetValue("test", 0);
    }
}

methodmap TestingB < TestingA
{
    public TestingB()
    {
        return view_as<TestingB>(new TestingA());
    }
}

TestingB g_Test = null;

public void OnPluginStart()
{
    g_Test = ReturnB();
}

TestingB ReturnB()
{
    return new TestingB();
}

public void OnConfigsExecuted()
{
    g_Test.Test();
}
```

---
### Output
```
SourcePawn Compiler 1.9.0.6280
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2017 AlliedModders LLC

Segmentation fault

SourcePawn Compiler 1.10.0.6405
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC



```

### Expected output
```
plugin.sp(1) : error 093: expected tag name identifier
```

Notice how the 1.10 compiler does not report segmentation fault, but I highly suspect it does so.
Also worth noting that this does not segfault when on https://spider.limetech.io/ (older version?)

**Comment by Fyren** [comment]
It's definitely smashing memory.  Whether that results in a segfault or terminating in some other way is probably just up to chance.  Spider will act differently in cases like this because it's JS running in your browser.  

This specific problem seems to be in the methodmap parsing at https://github.com/alliedmodders/sourcepawn/blob/5e1091f923880662466634a0794910dde104c61e/compiler/parser.cpp#L3652.  Not doing so appears to end up causing problems down the line.  Going to wait on pushing a change until checking into if the same problem exists in other places.
