### ISSUE TITLE
Legacy Enum Struct String Index Issues

### ISSUE THREAD

**Issue by Scags** [alliedmodders/sourcepawn#343]
Using old-style enum structs, Strings within them behave differently when getting a character index or string viewing.

```c#
enum FooBar
{
	String:Bar[32]
};

public void OnPluginStart()
{
	FooBar foo[FooBar];
	strcopy(foo[Bar], sizeof(foo[Bar]), "FooAndBar");
	for (int i = 0; i < strlen(foo[Bar]); ++i)
		PrintToServer("%s", foo[Bar][i]);
}
```

Outputs:
![Imgur Image](https://imgur.com/qtYo75s.png)

On SM 1.9.0.6281.
Fortunately, this seems to behave normally with the new-style enum structs.

**Comment by dvander** [comment]
Indeed this was explicitly fixed in the new style. For compatibility reasons it's probably best to leave the old broken code as-is.On Jul 10, 2019 4:56 PM, Scags <notifications@github.com> wrote:Using old-style enum structs, Strings within them behave differently when getting a character index or string viewing.
enum FooBar
{
	String:Bar[32]
};

public void OnPluginStart()
{
	FooBar foo[FooBar];
	strcopy(foo[Bar], sizeof(foo[Bar]), "FooAndBar");
	for (int i = 0; i < strlen(foo[Bar]); ++i)
		PrintToServer("%s", foo[Bar][i]);
}
Outputs:

On SM 1.9.0.6281.
Fortunately, this seems to behave normally with the new-style enum structs.

**Comment by peace-maker** [comment]
#327 and #328 are where this was discussed and fixed for new-style enum structs.
