### ISSUE TITLE
Shared Variables

### ISSUE THREAD

**Issue by TheByKotik** [alliedmodders/sourcepawn#414]
Description:
1. Created before call any callbacks on first plugin (who declare this variable) loaded and destroyed after last plugin (who declare this variable) unloaded.
2. Every plugin (who declare this variable) can change variable.
3. No one plugin not "own" this variable.

Example plugin one:
```
stock shared int gs_iSomeInt;
stock shared ArrayList gs_arrSomething;

public APLRes AskPluginLoad2 (Handle myself, bool late, char[] error, int err_max)
{
	if ( gs_arrSomething )
	{
		PrintToServer( "1: gs_arrSomething already created by other plugin. \nLength: %i", gs_arrSomething.Length );
	}
	else
	{
		gs_arrSomething = new ArrayList();
		gs_arrSomething.Push( 1 );
	}
	PrintToServer( "1: gs_iSomeInt = %i.", gs_iSomeInt );
	gs_iSomeInt = 1;
}
```
Example plugin two:
```
stock shared int gs_iSomeInt;
stock shared ArrayList gs_arrSomething;

public APLRes AskPluginLoad2 (Handle myself, bool late, char[] error, int err_max)
{
	if ( gs_arrSomething )
	{
		PrintToServer( "2: gs_arrSomething already created by other plugin. \nLength: %i", gs_arrSomething.Length );
	}
	else
	{
		gs_arrSomething = new ArrayList();
		gs_arrSomething.Push( 1 );
		gs_arrSomething.Push( 1 );
	}
	PrintToServer( "2: gs_iSomeInt = %i.", gs_iSomeInt );
	gs_iSomeInt = 2;
}
```

**Comment by asherkin** [comment]
What use case do you wish to fulfil using this feature? What is currently lacking in the language (or SM API) that makes it non-ideal?

My gut says this has all the (well known) problems of global state combined with all the problems of it being implicitly shared among (potentially unrelated) plugins - this is generally a pattern that modern languages (and APIs) are moving away from as quickly as possible.

**Comment by TheByKotik** [comment]
As an example for projects like sbpp:
1. For using one shared database handle and easy closing / open new for every module.
2. Shared char array for database prefix (for prevent read config file by every module).
In general, I want to use this so as not to create kludge of forwards / natives.

**Comment by Headline** [comment]
Thank you for thinking of future improvements to the language!

I'd have to say 👎 since this brings up issues with allocation ownership. The best way for this to be achieved would be with natives, whose syntax can be cleaned up with methodmaps :p

**Comment by dvander** [comment]
I agree with the other comments here, but I'll add something because I'd be on the hook for making it work: it's simply a *lot* of work to implement this, and it's a very esoteric feature, akin to weak or static linkage.

Using methodmaps, you could get something close to this syntax and then provide the getters/setters with a dedicated plugin. But for big, complex, shared resources - generally you don't want to rely on linkage to resolve ownership issues. It's better to have lightweight handles (like what an SQL connection is) and let the other side figure out how to protect it. The stock/helper method can create the handle for you.
