### ISSUE TITLE
Inconsistent modulo operator

### ISSUE THREAD

**Issue by zealain** [alliedmodders/sourcepawn#456]
```
int result = (0 + (-1)) % 128;
 => result = 127

int x = 0;
int result = (x + (-1)) % 128;
 => result = -1
```

Both calculations should return 127, or at the very least the same value.

Tested with SourcePawn Compiler 1.10.0.6460 and 1.11.0.6490

**Comment by asherkin** [comment]
Thanks for the report - it looks like the first one gets evaluated entirely at compile time, and the latter at runtime. It wouldn't surprise me if there were other oddities around division here.

**Comment by dvander** [comment]
Backstory- when faluco and I started SourcePawn (long before SourceMod) we added a few compiler hacks (function pointer, string/any tags, dynamic arrays), and built a new JIT. The old Pawn JIT was written in *self-modifying assembly*, and we had to refer to it a lot for guidance. faluco, a stickler for optimization, was confused by the implementation of `OP_SDIV` (the divide operator). Instead of just being the x86 `idiv` instruction, it was a non-inlined function call. The function itself was [16 instructions](https://github.com/alliedmodders/amxmodx/blob/master/amxmodx/amxjitsn.asm#L2175). "What on earth is going on here?" we wondered.

It turned out, Pawn has a particular definition of division:

> e1 / e2: Results in the division of e1 by e2. The result is truncated to the nearest integral value that is less than or equal to the quotient. Both negative and positive values are rounded towards −∞.

We didn't understand the point, and we *really* wanted to argue the new JIT was fast. So we shortened the implementation to a single "idiv" instruction. In the process, we forgot to update the compiler, which until your report and asherkin's diagnosis, has gone unnoticed.

I don't know which implementation is better. The current behavior matches C. The old behavior matches Python. Both versions preserve the relationship between the division and modulus operator:

    -1 / 128 = -1
    -1 % 128 = 127
    (128 * -1) + 127 = -1

    -1 / 128 = 0
    -1 % 128 = -1
    (0 * 128) + -1 = -1

For us, the runtime is definitive, so I'll fix the compiler to match.

**Comment by bottiger1** [comment]
So if I am understanding this correctly, you are going to make the behavior return a negative number instead of making sure it is 0 or positive?

**Comment by dvander** [comment]
The compile-time behavior (used for constant expressions) now matches the runtime behavior. When division would result in a non-integer number, the fractional portion is truncated toward 0. This is different from the compile-time behavior which used a floor operation rather than a truncate.

It's too late for us to change the runtime behavior (it's been baked into a decade of plugins by now), but we can always add natives that use the floor behavior.

**Comment by bottiger1** [comment]
Ok never mind then I will just make a function that adds the modulus to the dividend then.
