### ISSUE TITLE
Function type incorrectly initialized to 0 on enum structs

### ISSUE THREAD

**Issue by Sikarii** [alliedmodders/sourcepawn#469]
When initializing a variable of type `Function` in an enum struct, they seem to incorrectly default to 0.

I believe the Function type in this case **should** default to -1 (INVALID_FUNCTION) instead.

The following code results in:
- `Is null`: 1
- `Is INVALID_FUNCTION`: 0

```
enum struct MyStruct
{
    Function Handler;
}

public void OnPluginStart()
{
    MyStruct myStruct;

    PrintToServer("Is null: %d", (!!myStruct.Handler));
    PrintToServer("Is INVALID_FUNCTION: %d", (myStruct.Handler != INVALID_FUNCTION));
}
```

**Comment by dvander** [comment]
Thanks for the report. This is an annoying case, because variables are supposed to be zero'd by default, but both 0 and -1 are invalid values for a function variable. It's way too late to fix the fact that we picked -1 for INVALID_FUNCTION.

I'm tempted to make the comparison implicitly check for both. Until I can finish the array refactoring PR, it's probably the easier route.

**Comment by dvander** [comment]
This is now zero/null.
