### ISSUE TITLE
Compiler crash when defining function that's already a native

### ISSUE THREAD

**Issue by dysphie** [alliedmodders/sourcepawn#516]
When defining a function that is already defined as a native, spcomp crashes.

  * OS: Windows 10.0.19041
  * SourcePawn Compiler 1.11.0.6621

**Code:**

```cpp
#include <sourcemod>

void PrintToServer(const int[] test) 
{

}
```

**Comment by dvander** [comment]
Thanks for the reduced test case, this should be fixed now (as in, it won't crash, but the code will error). The error is not pretty, because like Fyren mentioned, the parser is leaving tokens on the floor. It's interleaving semantic checks with lexing which is exactly the what the new parser is trying to fix, but it will be a while before I can transition function parsing over.
