### ISSUE TITLE
Add AND-NOT operator "&^" from Golang

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcepawn#522]
At request of a developer, made this into an issue.

The `&^` operator clears a bit in an expression. Assignment equivalent: `&^=`

The following code are equivalent:
```golang
a &^ b;
```

```c
a & ~b;
```

likewise;
```c
a &^= b;
```

```c
a &= ~b;
```

Example usage:
```c
flags &^= FLAG_ENABLE;

...
/// clear player bits.
int effect;
for( int i=0; i<MaxPlayers; i++ ) {
    effect &^= i << 1;
}
```

In golang, the operator has the same precedence as multiplication, division, modulo, etc.

**Comment by dvander** [comment]
This has three strikes against it, as I see it:

One, it is sugar that saves at most three characters (a tilde and parens), so that's a whole new operator to learn and keep in the language headspace for no gain.

Two, it's called "AND NOT" but spelled "AND XOR". That is super confusing. I'm guessing this is a new feature, and because tilde is unary, they couldn't introduce a "&~" operator without breaking parsing. I would have picked "~&". (And maybe called it the hotdog pretzel operator?)

Three, Pawn has a lot of esoteric features. It doesn't want for more, and we've been actively trying to remove the weird ones and make it look more like industrial languages (like Java/C#).

Anyway - let's shelve this for now, since I think it is on the lower end of priorities for spcomp.
