### ISSUE TITLE
unsigned int

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#543]
Has any chances on implementing native support for basic type like `unsigned int`?

**Comment by Wend4r** [comment]
Following this, it can also be dependent on the need to add an `unsigned float`. Working with it at the floating point level.

**Comment by assyrianic** [comment]
maybe compact the name to `uint`

**Comment by dvander** [comment]
What's the use case for this?

**Comment by CrazyHackGUT** [comment]
For correct working with unsigned integers, i guess?

For example, in SM API exists native for retrieving Steam Account ID for players. Technically, this is unsigned integer, but we can get negative integer today or in near future.
Also in DB sometimes can be written unsigned integer.

**Comment by Wend4r** [comment]
With the Steam Account ID, I think there is no need to perform any math calculations, it would be sufficient to use a string in the `unsigned int` role of a number.
```sourcepawn
FormatEx(buffer, sizeof(buffer), "%u", account_id);
```

**Comment by CrazyHackGUT** [comment]
I just suggested. Currently, for me there is no any requirement in `uint`. For some SourcePawn scripters, who doesn't use GitHub, it may be need. In russian community, one guy created extension for working with `uint`'s: https://hlmod.ru/resources/2251/

**Comment by dvander** [comment]
There is, as far as I can tell, no mathematical need for unsigned numbers in SourcePawn. Wend4r references the fact that it is ultimately a display issue because the underlying data is identical. We already have an unsigned shift operator. Most other requests would be solved by having an int64 type. I do believe int64 is important, and there is a big refactoring PR that attempts to get us part of the way there.

In the meantime, I'm going to close this. If anyone has a stronger argument for unsigned ints (that are not solved by %u) please feel free to re-open.

**Comment by Fyren** [comment]
> In russian community, one guy created extension for working with `uint`'s: https://hlmod.ru/resources/2251/
 
> There is, as far as I can tell, no mathematical need for unsigned numbers in SourcePawn. Wend4r references the fact that it is ultimately a display issue because the underlying data is identical. 

To explain this a little more, if you're only doing addition, subtraction, or multiplication, you don't need to do anything different in SP.  You just use +, -, or * as normal and it doesn't matter if your values or unsigned or signed since that's just how two's complement works.  If you do division, you do have to deal with the high bit yourself, but that doesn't need an extension.

**Comment by CrazyHackGUT** [comment]
I understand, how unsigned type works, don't explain for me. I just noted.
