### ISSUE TITLE
'#assert' compiler directive seems to not work properly with enums

### ISSUE THREAD

**Issue by Natanel-Shitrit** [alliedmodders/sourcepawn#561]
`1.11.0.6516` compiler the following works fine: (didn't test any newer ones)

```
enum
{
    TEST_1,
    TEST_2,
    TEST_MAX
}

#assert TEST_MAX == TEST_MAX
```

But on `1.11.0.6675` compiler, this code above throws the following error:
```
fatal error 193: assertion failed: TEST_MAX == TEST_MAX
````

**Comment by Natanel-Shitrit** [comment]
Sorry for posting a half title, my fat fingers clicked on the `Enter` key 😄
Working on it now.

**Comment by dvander** [comment]
This was broken by the new enum parser.

**Comment by dvander** [comment]
The bug here is kind of heinous. Adding a semicolon to the closing brace makes it go away. Why? Because we optionally match a semicolon. If it's not there, we lex a token anyway to pre-populate the lexer buffer. This eats up the newline, and then proceeds to find the "#assert".

In 1.10, parsing and binding occurred in lock-step, so `TEST_MAX` was a valid constant when lexing the missing semicolon. In 1.11, parsing and binding are separate. `TEST_MAX` does not exist.

The real problem here is that using `#assert` in this way is illegal. Preprocessor values are not allowed to interact with anything other than values defined by the preprocessor. By definition a preprocessor runs before the parser. The fact that it worked up until now is a quirk exacerbated by Pawn's allowing constants in macro lookups.

I don't see any way (yet) to reconcile this and unfortunately I'm guessing reliance on this quirk is rather widespread.

My gut feeling is to make this an error in 1.12. And for now, issue a warning when a non-preprocessor symbol appears in a preprocessor expression. We can add a static_assert() builtin to achieve the end-goal here.

Let me know your thoughts.

**Comment by dvander** [comment]
Sample error message with a speculative fix applied:

```
test.sp(8) : warning 230: symbol "TEST_MAX" is not a preprocessor symbol; this behavior is undefined and will be removed in the future
test.sp(8) : error 017: undefined symbol "TEST_MAX"
test.sp(8) : fatal error 193: assertion failed: TEST_MAX == TEST_MAX
```

**Comment by c0rp3n** [comment]
Your suggested approach of making this case an error and adding a `static_assert` builtin seems a nice step forward.

**Comment by dvander** [comment]
This has been fixed on master.
