### ISSUE TITLE
"generative" Inline C(++) for SP code

### ISSUE THREAD

**Issue by assyrianic** [alliedmodders/sourcepawn#582]
Not really expecting to have this type of feature taken seriously but thought I'd brainstorm for a way to do "portable" extensions by having SP (or SM) shipped with a C++ compiler and registering a code of C++ as a string that would be then called within the SP function.

I'm imagining it something like:
```c
char cpp_codes[][] = {
    "int square(int x) { return x*x; }"
};
char native_names[][] = {
    "square"
};
RegisterInlineNatives(cpp_code, sizeof(cpp_code), native_names, sizeof(native_names), "my_extension_name.ext");
```
Where `RegisterInlineNative` will invoke a C++ native that then pipes the string code to a special script that will give the string code to the shipped compiler and creates an extension from that.

One foreseeable benefit is that it'll be easier to create and produce extensions directly from the scripting system without having to rely on building things before hand. There will still be the benefit that building extensions before hand will increase load up times. A (necessary evil) caveat that might be put in place, in order to make sure load times aren't a burden as well as keeping the importance of building extension before hand, is that extensions created from inline code will not be as optimized as an extension that was built before hand.

Another benefit is that this system will solve the burden of having to do separate building of extensions between OSs. Extensions no longer need to have individual linux or windows builds since the shipped C++ compiler can take care of that for you.

**Comment by dvander** [comment]
I think everyone can agree that C++ is a perfect language, immeasurable in its beauty. But there are a number of problems with inlining it into SourcePawn, the biggest of which is that C++ for [i]Source[/i] is not portable. There is no way to make Source-targeted extension code work everywhere. To even attempt that you'd need to ship 20+ SDKs along with every SourceMod install, something I'm guessing most server operators would not be too keen on.

You mention two problems you're trying to solve, that are really the same problem: extensions are difficult to maintain. They're hard to write, build, and distribute.

I think the right path to this problem is something like [url=https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke]P/Invoke[/url]. We'd definitely entertain attempts to sketch out a SourcePawn version of this API.
