### ISSUE TITLE
Compiler doesn't accepts multiple source files

### ISSUE THREAD

**Issue by CrazyHackGUT** [alliedmodders/sourcepawn#729]
I used this function to add git variables (like commit hash) to version, but in 1.11 it doesn't work.
If you try to pass any default SM plugins in version 1.10 or lower as arguments, you will get an error about "duplicating" functions like `OnPluginStart`, but in 1.11 it just compiles the first source passed:
![image](https://user-images.githubusercontent.com/12576822/143766224-f23e0b30-d8c2-4d29-ac2c-30035c5e8948.png)

Note that size isn't changed.

**Comment by asherkin** [comment]
This is an intentional change (see #637), and it was never a great way to do auto-versioning stuff (use `#tryinclude` like SM or include them on the compiler command line). I have seen it mentioned around the upgrading docs but it's not mentioned in https://github.com/alliedmodders/sourcepawn/blob/master/docs/upgrading-1.11.md currently.

**Comment by CrazyHackGUT** [comment]
> include them on the compiler command line

How perform this?

**Comment by dvander** [comment]
Indeed please use #tryinclude for this use case. If that doesn't work we can discuss further options. I don't want to bring back this feature because the way it worked was very hacky, and I don't want to build it back in without having clear use cases.
