### ISSUE TITLE
Error when attempting to compile a script with included files and a specific line count

### ISSUE THREAD

**Issue by Mikusch** [alliedmodders/sourcepawn#793]
On **SourcePawn Compiler 1.11.0.6876**

I am not sure what to title this because I do not know what causes this issue.

The below plugin produces an error: `test.sp(30) : error 155: expected newline, but found '#include'`. Yes, the huge comments are necessary to reproduce this.

If this wasn't strange enough already, adding or removing a new line before the commented lines causes it to compile again. I've tried to make the example as small as possible while still causing the compiler error.

**Main file:**
```sourcepawn
/*
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

#include "test_sub.sp"

#include "test_sub2.sp"
// Any code or new lines below this line do not affect the error.

public void OnPluginStart()
{
	Number(5).Print();
}
```

**test_sub.sp**
```sourcepawn
/*
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

methodmap Number
{
	public Number(int number)
	{
		return view_as<Number>(number);
	}
	
	public void Print()
	{
		PrintToServer("The number is: %d", view_as<int>(this));
	}
	// Putting a function below this point will allow it to compile again.
	// New lines, however, do not affect it.
}
```

**test_sub2.sp**
```
// The contents of this file do not matter, it just needs to be recognized as valid by spcomp
```

**Comment by Fyren** [comment]
Thanks for the report.  This was probably hard to whittle down to a test case.

The bug is the compiler was only checking line numbers to figure out if there was a newline between tokens.  It didn't check if the tokens were actually in different files.  To hit the bug, you had to end an include in something that cared about newlines (methodmaps require a semicolon or newline after the closing brace), plus the line number the include ended on had to match with the line number for the next token in the enclosing file.

**Comment by Fyren** [comment]
Fixed in SP.  Will be fixed in SM when SP is updated there.
