### ISSUE TITLE
Ternary char array format

### ISSUE THREAD

**Issue by JoinedSenses** [alliedmodders/sourcepawn#834]
Ternary doesnt operate as expected for this bit of code. Rather than producing the rest of the string, its just producing the character at the index
```sourcepawn
public void OnPluginStart() {
    char test[] = "Hello dear sir";
    char buf[256];
    Format(buf, sizeof(buf), "%s", test[0] ? test[4] : test[6]);
    PrintToServer("Buffer: %s", buf);
}
```

> Buffer: o

**Comment by assyrianic** [comment]
makes sense though, how do you specify that you're working with a slice as opposed to the value at the char array index?

**Comment by dvander** [comment]
The reason for this, as @assyrianic suggested, is that the ternary operator '?' converts l-values to r-values, which causes the character to be loaded rather than passed as an address.

Since that's been the behavior for a very long time now, I'd be reticent to change it. It could break existing plugins.
